 

#ifndef DRIVER_FLASH_H
#define DRIVER_FLASH_H

enum FLASH_READ_MODE {
    FLASH_READ_MODE_1_CYCLE,  
    FLASH_READ_MODE_2_CYCLE,  
};

typedef enum FLASH_READ_MODE FLASH_READ_MODE;

enum FLASH_MASK_SELECTION {
    FLASH_MASK_SELECTION_NONE,  
    FLASH_MASK_SELECTION_2KB ,  
    FLASH_MASK_SELECTION_4KB ,  
    FLASH_MASK_SELECTION_8KB ,  
};

typedef enum FLASH_MASK_SELECTION FLASH_MASK_SELECTION;

enum FLASH_MODE {
    FLASH_MODE_READ_AHB,  
    FLASH_MODE_PROGRAM ,  
    FLASH_MODE_ERASE   ,  
    FLASH_MODE_READ_APB,  
};

typedef enum FLASH_MODE FLASH_MODE;

enum FLASH_AREA {
    FLASH_AREA_MAIN,  
    FLASH_AREA_NVR ,  
};

typedef enum FLASH_AREA FLASH_AREA;

void FLASH_Init(FLASH_READ_MODE ReadMode);
void FLASH_ConfigureTrimValues(void);
uint32_t FLASH_ReadNvrWord(uint32_t Address);

#endif

